export const tables = Object.freeze({
  HK_DISTRICT: "hk_district",
  ROLE: "role",
  BANQUET_VENDOR_CAT: "banquet_vendor_cat",
  CHURCH_LIST: "church_list",
  BUDGET_CAT: "budgets_cat",
  BANQUET_VENDOR_LIST: "banquet_vendor_list",
  WEDDING_EVENT: "wedding_event",
  USER_INFO: "user_info",
  WEDDING_USER: "wedding_user",
  WEDDING_TO_DO_LIST: "wedding_to_do_list",
  WEDDING_LOGISTICS: "wedding_logistics",
  WEDDING_BUDGET_LIST: "wedding_budget_list",
  ITINERARY_LIST: "itinerary_list",
  ITINERARY_ROLE: "itinerary_role",
  WEDDING_USER_ITINERARY: "wedding_user_itinerary",
  LOGISTICS_LIST_TEMPLATE: "logistics_list_template",
  TO_DO_LIST_TEMPLATE: "to_do_list_template",
  ITIN_TEMPLATE: "itin_template",
  BUDGET_TEMPLATE: "budget_template",
  WEDDING_GUEST_LIST: "wedding_guest_list",
  MESSAGE_ROLE: "message_role",
  MESSAGE_LIST: "message_list",
  WEDDING_PARTI_LIST: "wedding_parti_list",
});
